### ISSUE TITLE
Bower cannot be run with sudo

### ISSUE THREAD

**Issue by vitalk** [vitalk/ansible-flaskapp#2]
When sudo enabled for role, bower command fail:

``` yaml

---
- name: My flask app
  hosts: web
  roles:
    - { role: vitalk.flaskapp, sudo: true }
```

Possible to fix this by explicitly use `bower --allow-root` or explicitly disable sudo for bower task.
